#!/bin/bash

user="$2"
timer="$3"

function ssh(){
    sleep ${timer}
	getent passwd ${user}  >/dev/null 2>&1
	userdel -f ${user}  >/dev/null 2>&1
	systemctl restart sshd >/dev/null 2>&1
	systemctl restart ws >/dev/null 2>&1
}

if [[ ${1} == "ssh" ]]; then
ssh
fi